mysite/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
	url(r'^$', include('mainPage.urls', namespace='mainPage')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^photos/$', include('photos.urls', namespace='photos')),
    url(r'^about/$', include('timeline.urls', namespace='about')),
    url(r'^blog/$', include('blog.urls', namespace='blog')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/timeline/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

mysite/blog/models.py
from django.db import models

# Create your models here.
class post(models.Model):
	body = models.TextField()
	title = models.CharField(max_length=255)
	subtitle = models.CharField(max_length=255)
	date = models.DateField()
	author = models.CharField(max_length=255)
	post_image = models.ImageField(upload_to='blog')
	author_image = models.ImageField(upload_to='blog')

	def __str__(self):
		return self.title

mysite/mainPage/models.py
from django.db import models

# Create your models here.

class Panel(models.Model):
	info = models.CharField(max_length=200)

mysite/photos/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mysite/timeline/models.py
from django.db import models

# Create your models here.

mysite/mainPage/forms.py
from django import forms

class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import *

def index(request):
	posts = post.objects.order_by('-date')
	context = {'posts':posts}
	return render(request, 'blog/index.html', context)

mysite/mainPage/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from django.template.loader import get_template
from django.core.mail import EmailMessage, send_mail
from django.template import Context

from .models import *
from .forms import ContactForm

def index(request):
	form_class = ContactForm
	context = {'form':form_class}

	if request.method == 'POST':
		form = form_class(data=request.POST)

		if form.is_valid():
			contact_name = request.POST.get('contact_name', '')
			contact_email = request.POST.get('contact_email', '')
			form_content = request.POST.get('content', '')

			print contact_name, contact_email, form_content

			send_mail(
				'Email from website, from '+ contact_name,  #subject
				contact_email + " \n" + form_content,   #message
				'richardxupersonal@gmail.com',   #from
				['richardxu@berkeley.edu', 'richardxupersonal@gmail.com'],    #to
				fail_silently=False,
			)
            # Email the profile with the 
            # contact information
            # template = get_template('contact_template.txt')
            # context = Context({
            #     'contact_name': contact_name,
            #     'contact_email': contact_email,
            #     'form_content': form_content,
            # })
            # content = template.render(context)

            # email = EmailMessage(
            #     "New contact form submission",
            #     content,
            #     "Your website" +'',
            #     ['kocepudim@stexsy.com'],
            #     headers = {'Reply-To': contact_email }
            # )
            # email.send()
			# msg = EmailMessage('Request Callback', 'Here is the message.', to=['kocepudim@stexsy.com'])
			# msg.send()
			return redirect('mainPage:index')


	return render(request, 'mainPage/index.html', context)

mysite/photos/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import *

import requests
import json


user_id = '139169754@N02'
api_key = '41dd3aff041c00c52febdef9786a9ca0'
api_secret = '0f5a3b5047f760f7'

def index(request):
	context = {}
	context['photos'] = []

	method = 'flickr.people.getPublicPhotos'
	query = 'https://api.flickr.com/services/rest/?&method=%s&api_key=%s&user_id=%s&format=json&nojsoncallback=1'%(method, api_key, user_id)
	query += '&extras=url_z'

	response = requests.get(query)
	if response.ok:
		response = json.loads(response.text)
	
		for link in response['photos']['photo']:
			context['photos'].append(str(link['url_z']))

	return render(request, 'photos/index.html', context)

mysite/timeline/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	context = {}
	return render(request, 'timeline/index.html', context)

mysite/templates/blog/index.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>Richard Xu</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'mainPage/assets/css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'blog/main.css' %}" />
		<style type="text/css">
		@font-face {
			font-family: 'ManhattanDarling';
			font-style: normal;
			font-weight: normal;
			src: url("{% static 'mainPage/ManhattanDarling/OTF/ManhattanDarling-Regular.otf' %}") format('truetype');
		}
		</style>
	</head>
	<body>

		<!-- Page Wrapper -->
			<div id="page-wrapper">

				<!-- Header -->
					<header id="header" class="alt">
						<h1><a href="{% url 'mainPage:index' %}" style="font-family:ManhattanDarling; font-size:150%">Richard Xu</a></h1>
						<nav>
							<a href="#menu">Menu</a>
						</nav>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<div class="inner">
							<h2>Menu</h2>
							<ul class="links">
								<li><a href="{% url 'mainPage:index' %}">Home</a></li>
								<li><a href="{% url 'about:index' %}">About Me</a></li>
								<li><a href="{% url 'photos:index' %}">Photography</a></li>
								<li><a href="{% url 'blog:index' %}">Blog</a></li>
							</ul>
							<a href="#" class="close">Close</a>
						</div>
					</nav>

				<!-- Banner -->
					<section id="banner" style="background: linear-gradient( rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4) ), url({% static 'mainPage/images/background2.jpg'%}); background-size: 100%;">
						<div class="inner">
							<div class="logo"><span class="icon" ><img src="{% static 'mainPage/images/RX-white.png' %}" style="height:50%; width:50%;text-align: center;margin-top:25%"></span></div>
							<h2 style="font-family: ManhattanDarling, Helvetica, sans-serif;font-size:4em;letter-spacing: 0.2em;">Richard Xu</h2>
							<p> Just my personal blog. <br>
								Updated occasionally </p>
						</div>
					</section>

				<section id="one" class="wrapper spotlight style3">
				<!-- Wrapper -->
					<section id="wrapper">
								<div id="main">
									{% for post in posts %}
								<!-- Post -->
									<article class="post" style="color:black">
										<header>
											<div class="title">
												<h2 style="color:black">{{ post.title }}</h2>
												<p>{{ post.subtitle }}</p>
											</div>
											<div class="meta">
												<time class="published" datetime="2015-11-01">{{ post.date }}</time>
												<span class="author"> &nbsp {{ post.author }} &nbsp <img src="{{ post.author_image.url }}" alt="" style="width: 3.5em;border-radius: 100%;"/> </span> 
											</div>
										</header>
										<a class="fimage featured"><img src="{{ post.post_image.url }}" alt="" style="object-fit: cover;height:30em"/></a>
										<p>{{ post.body }}</p>
									</article>
									{% endfor %}

								</div>
					</section>
				</section>

			</div>

		<!-- Scripts -->
			<script src="{% static 'mainPage/assets/js/skel.min.js' %}"></script>
			<script src="{% static 'mainPage/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'mainPage/assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'mainPage/assets/js/util.js' %}"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="{% static 'mainPage/assets/js/main.js' %}"></script>

	</body>
</html>

mysite/templates/mainPage/index.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>Richard Xu</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'mainPage/assets/css/main.css' %}" />
		<style type="text/css">
		@font-face {
			font-family: 'ManhattanDarling';
			font-style: normal;
			font-weight: normal;
			src: url("{% static 'mainPage/ManhattanDarling/OTF/ManhattanDarling-Regular.otf' %}") format('truetype');
		}
		</style>
	</head>
	<body>

		<!-- Page Wrapper -->
			<div id="page-wrapper">

				<!-- Header -->
					<header id="header" class="alt">
						<h1><a href="{% url 'mainPage:index' %}" style="font-family:ManhattanDarling; font-size:150%">Richard Xu</a></h1>
						<nav>
							<a href="#menu">Menu</a>
						</nav>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<div class="inner">
							<h2>Menu</h2>
							<ul class="links">
								<li><a href="{% url 'mainPage:index' %}">Home</a></li>
								<li><a href="{% url 'about:index' %}">About Me</a></li>
								<li><a href="{% url 'photos:index' %}">Photography</a></li>
								<li><a href="{% url 'blog:index' %}">Blog</a></li>
							</ul>
							<a href="#" class="close">Close</a>
						</div>
					</nav>

				<!-- Banner -->
					<section id="banner" style="background-image: url({% static 'mainPage/images/background.jpg'%});background-size: 100% 100%;">
						<div class="inner">
							<div class="logo"><span class="icon" ><img src="{% static 'mainPage/images/RX-white.png' %}" style="height:50%; width:50%;text-align: center;margin-top:25%"></span></div>
							<h2 style="font-family: ManhattanDarling, Helvetica, sans-serif;font-size:4em;letter-spacing: 0.2em;">Richard Xu</h2>
							<p> Bioengineer | Software Engineer | Photographer</p>
						</div>
					</section>

				<!-- Wrapper -->
					<section id="wrapper">

						<!-- One -->
							<section id="one" class="wrapper spotlight style1">
								<div class="inner">
									<a href="#" class="image"><img src="{% static 'mainPage/images/panels/me.jpg'%}" alt="" /></a>
									<div class="content">
										<h2 class="major">A Little About Me</h2>
										<p>I am a senior at the University of California, Berkeley, majoring in Bioengineering and minoring in EECS. </p>
										<a href="{% url 'about:index' %}" class="special">Look at what I've done!</a>
										<a href="#" class="special">Resume</a>
									</div>
								</div>
							</section>

						<!-- Two -->
							<section id="two" class="wrapper alt spotlight style2">
								<div class="inner">
									<a class="image"><img src="{% static 'mainPage/images/panels/bioe.jpg'%}" alt="" /></a>
									<div class="content">
										<h2 class="major">Bioengineering</h2>
										<p>I am in the computational Biology concentration of bioengineering, and am specifically interested in protein interaction modeling. Previously I have worked in the Teresa Head-Gordon Lab applying the Poisson-Boltzmann Semi-Analytical Method onto polymer models. </p>
										<!-- <a href="#" class="special">Learn more</a> -->
									</div>
								</div>
							</section>

						<!-- Three -->
							<section id="three" class="wrapper spotlight style3">
								<div class="inner">
									<a href="#" class="image"><img src="{% static 'mainPage/images/panels/cs.jpg'%}" alt="" /></a>
									<div class="content">
										<h2 class="major">Software Engineering</h2>
										<p>Software is an amazing tool that allows us to solve bigger and harder problems. It lets us find the shortest path to our next class, sort our busy schedules and stream the next big meme. But I think software engineering can be used for even bigger and better things, like modeling protein folding or connecting the world or even getting us to Mars. And I want to be a part of this process.</p>
										<a href="https://github.com/xurichard" class="special">Github</a>
									</div>
								</div>
							</section>

						<!-- Four -->
							<section id="four" class="wrapper alt spotlight style4">
								<div class="inner">
									<a href="https://www.flickr.com/photos/richardxu/" class="image"><img src="{% static 'mainPage/images/panels/photography.jpg'%}" alt="" /></a>
									<div class="content">
										<h2 class="major">Photography</h2>
										<p>One of my biggest hobbies is photography (and all the photos on this website were taken by me). I think that a photo not only lets us capture the moment, but </p>
										<a href="https://www.flickr.com/photos/richardxu/" class="special">Flickr</a>
									</div>
								</div>
							</section>

						<!-- Four -->
							<!-- <section id="four" class="wrapper alt style1">
								<div class="inner">
									<h2 class="major">Vitae phasellus</h2>
									<p>Cras mattis ante fermentum, malesuada neque vitae, eleifend erat. Phasellus non pulvinar erat. Fusce tincidunt, nisl eget mattis egestas, purus ipsum consequat orci, sit amet lobortis lorem lacus in tellus. Sed ac elementum arcu. Quisque placerat auctor laoreet.</p>
									<section class="features">
										<article>
											<a href="#" class="image"><img src="images/pic04.jpg" alt="" /></a>
											<h3 class="major">Sed feugiat lorem</h3>
											<p>Lorem ipsum dolor sit amet, consectetur adipiscing vehicula id nulla dignissim dapibus ultrices.</p>
											<a href="#" class="special">Learn more</a>
										</article>
										<article>
											<a href="#" class="image"><img src="images/pic05.jpg" alt="" /></a>
											<h3 class="major">Nisl placerat</h3>
											<p>Lorem ipsum dolor sit amet, consectetur adipiscing vehicula id nulla dignissim dapibus ultrices.</p>
											<a href="#" class="special">Learn more</a>
										</article>
										<article>
											<a href="#" class="image"><img src="images/pic06.jpg" alt="" /></a>
											<h3 class="major">Ante fermentum</h3>
											<p>Lorem ipsum dolor sit amet, consectetur adipiscing vehicula id nulla dignissim dapibus ultrices.</p>
											<a href="#" class="special">Learn more</a>
										</article>
										<article>
											<a href="#" class="image"><img src="images/pic07.jpg" alt="" /></a>
											<h3 class="major">Fusce consequat</h3>
											<p>Lorem ipsum dolor sit amet, consectetur adipiscing vehicula id nulla dignissim dapibus ultrices.</p>
											<a href="#" class="special">Learn more</a>
										</article>
									</section>
									<ul class="actions">
										<li><a href="#" class="button">Browse All</a></li>
									</ul>
								</div>
							</section> -->

					</section>

				<!-- Footer -->
					<section id="footer" style="background: linear-gradient( rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4) ), url({% static 'mainPage/images/bg4.jpg'%}); background-size: 100%;">
						<div class="inner">
							<h2 class="major">Contact Me</h2>
							<p>Don't be shy, give it to me.</p>
							<form method="post" action="">
								{% csrf_token %}
								{{ form.as_p }}
								<!-- <div class="field">
									<label for="name">Name</label>
									<input type="text" name="name" id="name" />
								</div>
								<div class="field">
									<label for="email">Email</label>
									<input type="email" name="email" id="email" />
								</div>
								<div class="field">
									<label for="message">Message</label>
									<textarea name="message" id="message" rows="4"></textarea>
								</div> -->
								<ul class="actions">
									<li><input type="submit" value="Send Message" /></li>
								</ul>
							</form>
							<ul class="contact">
								<li class="fa-home">
									My Apartment<br />
									Apt.303 <br />
									2703 Ridge Rd.<br />
									Berkeley, CA 94709
								</li>
								<li class="fa-phone">(425) 623-6872</li>
								<li class="fa-envelope"><a href="#">richardxu@berkeley.edu</a></li>
								<li class="fa-instagram"><a href="https://www.instagram.com/richardxuxu/">richardxuxu</a></li>
								<li class="fa-linkedin"><a href="https://www.linkedin.com/in/richardxu1">richardxu1</a></li>
								<li class="fa-github"><a href="https://github.com/xurichard">xurichard</a></li>
							</ul>
							<ul class="copyright">
								<li>&copy; Untitled Inc. All rights reserved.</li><li>Richard Xu</a></li>
							</ul>
						</div>
					</section>

			</div>

		<!-- Scripts -->
			<script src="{% static 'mainPage/assets/js/skel.min.js' %}"></script>
			<script src="{% static 'mainPage/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'mainPage/assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'mainPage/assets/js/util.js' %}"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="{% static 'mainPage/assets/js/main.js' %}"></script>

	</body>
</html>

mysite/templates/photos/index.html
{% load static %}

<html>
	<head>
		<title>Richard Xu</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'mainPage/assets/css/main.css' %}" />
		<style type="text/css">
		@font-face {
			font-family: 'ManhattanDarling';
			font-style: normal;
			font-weight: normal;
			src: url("{% static 'mainPage/ManhattanDarling/OTF/ManhattanDarling-Regular.otf' %}") format('truetype');
		}
		</style>
		<link rel='stylesheet' href="{% static 'photos/index.css' %}">
	</head>

	<body>
		<!-- Page Wrapper -->
			<div id="page-wrapper">

				<!-- Header -->
					<header id="header" class="alt">
						<h1><a href="{% url 'mainPage:index' %}" style="font-family:ManhattanDarling; font-size:150%">Richard Xu</a></h1>
						<nav>
							<a href="#menu">Menu</a>
						</nav>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<div class="inner">
							<h2>Menu</h2>
							<ul class="links">
								<li><a href="{% url 'mainPage:index' %}">Home</a></li>
								<li><a href="{% url 'about:index' %}">About Me</a></li>
								<li><a href="{% url 'photos:index' %}">Photography</a></li>
								<li><a href="{% url 'blog:index' %}">Blog</a></li>
							</ul>
							<a href="#" class="close">Close</a>
						</div>
					</nav>

				<!-- Banner -->
					<section id="banner" style="background: linear-gradient( rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4) ), url({% static 'mainPage/images/background3.jpg'%}); background-size: 100%;">
						<div class="inner">
							<div class="logo"><span class="icon" ><img src="{% static 'mainPage/images/RX-white.png' %}" style="height:50%; width:50%;text-align: center;margin-top:25%"></span></div>
							<h2 style="font-family: ManhattanDarling, Helvetica, sans-serif;font-size:4em;letter-spacing: 0.2em;">Photography</h2>
							<p>Photos. Hit the bottom and keep scrolling. <br>I'm also gonna leave this here: <a href="https://www.flickr.com/photos/richardxu/">flickr</a></p>
						</div>
					</section>

					<section id="wrapper">
							<section id="one" class="wrapper spotlight style2">
								<div id="container" style="background-color:#FEDCD2;">
								</div>
							</section>

					</section>
			</div>
	</body>

	<script src="{% static 'mainPage/assets/js/skel.min.js' %}"></script>
	<script src="{% static 'mainPage/assets/js/jquery.min.js' %}"></script>
	<script src="{% static 'mainPage/assets/js/jquery.scrollex.min.js' %}"></script>
	<script src="{% static 'mainPage/assets/js/util.js' %}"></script>
	<script src="{% static 'mainPage/assets/js/main.js' %}"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
	<script src="https://npmcdn.com/masonry-layout@4.1/dist/masonry.pkgd.min.js"></script>
	<script src="https://npmcdn.com/imagesloaded@4.1.0/imagesloaded.pkgd.min.js"></script>
	<script src="{% static 'photos/index.js' %}"></script>
	<script>
		var all_photos = {{ photos|safe }};
		var all_photos_index = 0;

		appendPhotos(10);
	</script>
</html>